### ISSUE TITLE
custom plot_naming

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/cassbase#1]
Andreas: Then I have a question about generating randomized blocks. cassbase generates for the plot names continuous numbers. For logistics we would be interested to have separate numbering for each plot combined with the block number. So, for example block 1 has plots 101-106, block 10 has plots 1001 - 1006 etc.

**Comment by bauchetg** [comment]
There is a similar need in cassavabase. Here is the numbering structure we should preferably use (scalable for large trials): block one: 1001, block2: 2001, block3: 3001 and so on. Could this format be compliant with cassbase needs as well ?

**Comment by nickmorales** [comment]
ended up not be necessary here. plot_names are just unique identifiers
