### ISSUE TITLE
agronomic traits at plant level

### ISSUE THREAD

**Issue by nickmorales** [solgenomics/cassbase#3]
CASS needs 4 agronomic traits at the plant level:
fresh root weight
fresh shoot weight
fresh total weight
harvest index

These 4 terms also need to be composed with already used plant age terms.

**Comment by nmenda** [comment]
those terms exist in the ontology, but maybe the definition needs tweaking. 
Please add here the definitions that need updating

**Comment by nickmorales** [comment]
Harvest index is okay: https://www.cassavabase.org/cvterm/70668/view
Fresh root weight should not say plot in the definition: https://www.cassavabase.org/cvterm/70666/view
Fresh shoot weight should not say plot in the def: https://www.cassavabase.org/cvterm/70773/view
I can't find 'fresh total weight' so it may need to be added.

**Comment by nickmorales** [comment]
moved to: https://github.com/solgenomics/cassava/issues/4
